# @package hydra.launcher
partition: ml_gpu-rtx2080   # CHANGE ME
#account: mlgpu01    # CHANGE ME
exclude:
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 180
cpus_per_task: 8
#num_gpus: null
tasks_per_node: 1
mem_gb: 8
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
qos: null
comment: null
constraint: null
gres: gpu:1
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  #export: PATH,USER,SUBMITIT_EXECUTOR,SLURM_MPI_TYPE=pmi2,LD_LIBRARY_PATH
array_parallelism: 256
setup: null